apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ping-client
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ping-client
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
