apiVersion: v1
kind: Service
metadata:
  labels:
    tier: pong-server
  name: pong-server
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: pong-server
  type: NodePort
