apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pong-server
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pong-server
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50